---

- name: "2.1.3.2 | PATCH | Ensure systemd-timesyncd is enabled and running"
  ansible.builtin.systemd:
      name: systemd-timesyncd
      state: started
      enabled: true
      masked: false
  when:
      - ubtu22cis_rule_2_1_3_2
  tags:
      - level1-server
      - level1-workstation
      - rule_2.1.3.2
      - timesyncd
