---

- name: "1.5.1 | PATCH | Ensure address space layout randomization (ASLR) is enabled | Set active kernel parameter"
  ansible.posix.sysctl:
      name: kernel.randomize_va_space
      value: '2'
  when:
      - ubtu22cis_rule_1_5_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.5.1
      - aslr

- name: "1.5.2 | PATCH | Ensure prelink is not installed"
  block:
      - name: "1.5.2 | PATCH | Ensure prelink is not installed | Restore binaries to normal"
        ansible.builtin.shell: prelink -ua
        changed_when: false
        failed_when: false

      - name: "1.5.2 | PATCH | Ensure prelink is not installed| Remove prelink package"
        ansible.builtin.package:
            name: prelink
            state: absent
  when:
      - ubtu22cis_rule_1_5_2
      - "'prelink' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.5.2
      - prelink

- name: "1.5.3 | PATCH | Ensure Automatic Error Reporting is not enabled"
  block:
      - name: "1.5.3 | PATCH | Ensure Automatic Error Reporting is not enabled | disable"
        ansible.builtin.lineinfile:
            path: /etc/default/apport
            regexp: ^enabled
            line: enabled=0
            create: true
            owner: root
            group: root
            mode: 0644

      - name: "1.5.3 | PATCH | Ensure Automatic Error Reporting is not enabled | remove package"
        ansible.builtin.package:
            name: apport
            state: absent
        when:
            - "'apport' in ansible_facts.packages"
  when:
      - ubtu22cis_rule_1_5_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.5.3
      - apport