---

- name: "1.4.3 | PATCH | Ensure authentication required for single user mode"
  ansible.builtin.user:
      name: "{{ ubtu22cis_grub_user }}"
      password: "{{ ubtu22cis_grub_user_passwd }}"
  when:
      - ubtu22cis_rule_1_4_3
      - ubtu22cis_set_grub_user_pass
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.3
      - passwd
      - grub
